name:                ldgallery-compiler
version:             2.3
homepage:            https://ldgallery.pacien.org
github:              "pacien/ldgallery"
license:             AGPL-3.0-only
author:              "Pacien TRAN-GIRARD, Guillaume FOUET"
copyright:           "2019-2023 Pacien TRAN-GIRARD, Guillaume FOUET"

extra-source-files:
- readme.md

# Metadata used when publishing your package
synopsis:            A static generator which turns a collection of tagged pictures into a searchable web gallery
category:            Web
description:         Please see the project's website at <https://ldgallery.pacien.org>

dependencies:
- base >= 4.7 && < 5
- containers
- data-ordlist
- filepath
- directory
- text
- aeson
- yaml
- cmdargs
- parallel-io
- Glob
- safe
- time
- process

default-extensions:
- DuplicateRecordFields
- DisambiguateRecordFields
- OverloadedRecordDot
- DeriveGeneric
- DeriveDataTypeable
- DeriveAnyClass
- FlexibleContexts
- NamedFieldPuns
- OverloadedStrings

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-uni-patterns
- -Wredundant-constraints

data-dir: data
data-files: ["**/*"]

library:
  source-dirs: src

flags:
  portable:
    description: >
      Make the output binary portable.
      It will look in its own runtime location for its assets instead of
      absolute installation paths.
    manual: true
    default: false

executables:
  ldgallery:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldgallery-compiler
    when:
    - condition: flag(portable)
      cpp-options: -DFLAG_PORTABLE

tests:
  ldgallery-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldgallery-compiler
