name:                ldgallery-compiler
version:             2.0
homepage:            https://ldgallery.pacien.org
github:              "pacien/ldgallery"
license:             AGPL-3
author:              "Pacien TRAN-GIRARD, Guillaume FOUET"
maintainer:          ""
copyright:           "2019-2020 Pacien TRAN-GIRARD, Guillaume FOUET"

extra-source-files:
- readme.md

# Metadata used when publishing your package
synopsis:            A static generator which turns a collection of tagged pictures into a searchable web gallery
category:            Web
description:         Please see the project's website at <https://ldgallery.pacien.org>

dependencies:
- base >= 4.7 && < 5
- containers
- data-ordlist
- filepath
- directory
- text
- aeson
- yaml
- cmdargs
- parallel-io
- Glob
- safe
- time
- process

default-extensions:
- DuplicateRecordFields
- DeriveGeneric
- DeriveDataTypeable
- DeriveAnyClass
- FlexibleContexts
- NamedFieldPuns
- OverloadedStrings

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-uni-patterns
- -Wredundant-constraints

data-dir: data
data-files: ["**/*"]

library:
  source-dirs: src

executables:
  ldgallery:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldgallery-compiler

tests:
  ldgallery-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldgallery-compiler
