name:                ldgallery-compiler
version:             0.1.0.0
github:              "pacien/ldgallery"
license:             AGPL-3
author:              "Pacien TRAN-GIRARD, Guillaume FOUET"
maintainer:          ""
copyright:           "2019 Pacien TRAN-GIRARD, Guillaume FOUET"

extra-source-files:
- readme.md

# Metadata used when publishing your package
synopsis:            A static generator which turns a collection of tagged pictures into a searchable web gallery
category:            Web
description:         Please see the README on GitHub at <https://github.com/pacien/ldgallery>

dependencies:
- base >= 4.7 && < 5
- containers
- filepath
- directory
- text
- aeson
- yaml
- optparse-applicative
- JuicyPixels
- JuicyPixels-extra

library:
  source-dirs: src

executables:
  ldgallery-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldgallery-compiler

tests:
  ldgallery-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ldgallery-compiler
